export const LESSON_DETAILS = {
  1: {
    id: 1,
    title: "Bài 3",
    topic: "Chó",
    author: "Duong Trần",
    totalTerms: 50,
    avatar: "👤",
    image: "🐕",
    slides: [
      { id: 1, word: "Chó", meaning: "Dog" },
      { id: 2, word: "Mèo", meaning: "Cat" },
      { id: 3, word: "Chim", meaning: "Bird" },
      { id: 4, word: "Cá", meaning: "Fish" },
      { id: 5, word: "Thỏ", meaning: "Rabbit" },
    ],
    flashcards: [
      { id: 1, english: "Dog", vietnamese: "Chó" },
      { id: 2, english: "Cat", vietnamese: "Con mèo" },
      { id: 3, english: "Bird", vietnamese: "Chim" },
      { id: 4, english: "Fish", vietnamese: "Cá" },
      { id: 5, english: "Rabbit", vietnamese: "Thỏ" },
      { id: 6, english: "Elephant", vietnamese: "Voi" },
      { id: 7, english: "Lion", vietnamese: "Sư tử" },
      { id: 8, english: "Tiger", vietnamese: "Hổ" },
      { id: 9, english: "Bear", vietnamese: "Gấu" },
      { id: 10, english: "Monkey", vietnamese: "Khỉ" },
    ],
  },
  2: {
    id: 2,
    title: "Bài 2",
    topic: "Thức ăn",
    author: "Bạn",
    totalTerms: 40,
    avatar: "👤",
    image: "🍎",
    slides: [
      { id: 1, word: "Apple", meaning: "Táo" },
      { id: 2, word: "Banana", meaning: "Chuối" },
      { id: 3, word: "Orange", meaning: "Cam" },
      { id: 4, word: "Rice", meaning: "Gạo" },
      { id: 5, word: "Bread", meaning: "Bánh mì" },
    ],
    flashcards: [
      { id: 1, english: "Apple", vietnamese: "Táo" },
      { id: 2, english: "Banana", vietnamese: "Chuối" },
      { id: 3, english: "Orange", vietnamese: "Cam" },
      { id: 4, english: "Rice", vietnamese: "Gạo" },
      { id: 5, english: "Bread", vietnamese: "Bánh mì" },
    ],
  },
  3: {
    id: 3,
    title: "Bài 1",
    topic: "Môn học",
    author: "Bạn",
    totalTerms: 35,
    avatar: "👤",
    image: "📚",
    slides: [
      { id: 1, word: "English", meaning: "Tiếng Anh" },
      { id: 2, word: "Mathematics", meaning: "Toán học" },
      { id: 3, word: "Science", meaning: "Khoa học" },
      { id: 4, word: "History", meaning: "Lịch sử" },
      { id: 5, word: "Geography", meaning: "Địa lý" },
    ],
    flashcards: [
      { id: 1, english: "English", vietnamese: "Tiếng Anh" },
      { id: 2, english: "Mathematics", vietnamese: "Toán học" },
      { id: 3, english: "Science", vietnamese: "Khoa học" },
      { id: 4, english: "History", vietnamese: "Lịch sử" },
      { id: 5, english: "Geography", vietnamese: "Địa lý" },
    ],
  },
  4: {
    id: 4,
    title: "Tiếng anh",
    topic: "Tạo phong",
    author: "Hùng",
    totalTerms: 30,
    avatar: "👤",
    image: "🌍",
    slides: [
      { id: 1, word: "Hello", meaning: "Xin chào" },
      { id: 2, word: "Good morning", meaning: "Chào buổi sáng" },
      { id: 3, word: "Thank you", meaning: "Cảm ơn" },
      { id: 4, word: "Please", meaning: "Vui lòng" },
      { id: 5, word: "Sorry", meaning: "Xin lỗi" },
    ],
    flashcards: [
      { id: 1, english: "Hello", vietnamese: "Xin chào" },
      { id: 2, english: "Good morning", vietnamese: "Chào buổi sáng" },
      { id: 3, english: "Thank you", vietnamese: "Cảm ơn" },
      { id: 4, english: "Please", vietnamese: "Vui lòng" },
      { id: 5, english: "Sorry", vietnamese: "Xin lỗi" },
    ],
  },
};

export const LESSON_MENU_ITEMS = [
  { id: 1, label: "Chế độ tập trung", icon: "folder" },
  { id: 2, label: "Bài tập ôn tập", icon: "document" },
  { id: 3, label: "Hỏi AI", icon: "chatbubble" },
];
